Python 3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> # Import packages
... import numpy as np
... import pandas as pd
... from scipy import stats
... 
... # Read in housing data
... brooklyn_one_bed = pd.read_csv('brooklyn-one-bed.csv')
... brooklyn_price = brooklyn_one_bed['rent']
... 
... manhattan_one_bed = pd.read_csv('manhattan-one-bed.csv')
... manhattan_price = manhattan_one_bed['rent']
... 
... queens_one_bed = pd.read_csv('queens-one-bed.csv')
... queens_price = queens_one_bed['rent']
... 
... # Add mean calculations below 
... 
... 
... 
... # Add median calculations below
... 
... 
... 
... # Add mode calculations below
... 
... 
... 
... 
... 
... 
... 
... 
... ##############################################
... ##############################################
... ##############################################
... 
... 
... 
... 
... 
... 
... 
... # Don't look below here
... # Mean
... try:
...     print("The mean price in Brooklyn is " + str(round(brooklyn_mean, 2)))
... except NameError:
...     print("The mean price in Brooklyn is not yet defined.")
... try:
...     print("The mean price in Manhattan is " + str(round(manhattan_mean, 2)))
... except NameError:
...     print("The mean in Manhattan is not yet defined.")
... try:
...     print("The mean price in Queens is " + str(round(queens_mean, 2)))
... except NameError:
...     print("The mean price in Queens is not yet defined.")
...     
...     
... # Median
... try:
...     print("The median price in Brooklyn is " + str(brooklyn_median))
... except NameError:
...     print("The median price in Brooklyn is not yet defined.")
... try:
...     print("The median price in Manhattan is " + str(manhattan_median))
... except NameError:
...     print("The median price in Manhattan is not yet defined.")
... try:
...     print("The median price in Queens is " + str(queens_median))
... except NameError:
...     print("The median price in Queens is not yet defined.")
...     
...     
... #Mode
... try:
...     print("The mode price in Brooklyn is " + str(brooklyn_mode[0][0]) + " and it appears " + str(brooklyn_mode[1][0]) + " times out of " + str(len(brooklyn_price)))
... except NameError:
...     print("The mode price in Brooklyn is not yet defined.")
... try:
...     print("The mode price in Manhattan is " + str(manhattan_mode[0][0]) + " and it appears " + str(manhattan_mode[1][0]) + " times out of " + str(len(manhattan_price)))
... except NameError:
...     print("The mode price in Manhattan is not yet defined.")
... try:
...     print("The mode price in Queens is " + str(queens_mode[0][0]) + " and it appears " + str(queens_mode[1][0]) + " times out of " + str(len(queens_price)))
... except NameError:
...     print("The mode price in Queens is not yet defined.")
... 
... 
